version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules # Anonymous volume to prevent host node_modules from overriding container's
    environment:
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      # This ensures the backend connects to the MongoDB service within the Docker network
      MONGODB_URI: mongodb://mongodb:27017/beyondbmi
    depends_on:
      - mongodb
    networks:
      - beyondbmi-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017" # Expose MongoDB port if you need to access it from host
    volumes:
      - mongodb_data:/data/db # Persist MongoDB data
    networks:
      - beyondbmi-network

volumes:
  mongodb_data:

networks:
  beyondbmi-network:
    driver: bridge